<?php

namespace App\Filament\Resources\Waves\Schemas;

use App\Models\WaveSetting;
use Filament\Forms\Components\DatePicker;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\TextInput;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Schema;

class WaveForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                Section::make('Wave Details')
                    ->description('Wave information (auto-generated by wms:generate-waves command)')
                    ->schema([
                        Select::make('wms_wave_setting_id')
                            ->label('Wave Setting')
                            ->options(WaveSetting::all()->pluck('id', 'id'))
                            ->required()
                            ->disabled()
                            ->dehydrated(),

                        TextInput::make('wave_no')
                            ->label('Wave Number')
                            ->disabled()
                            ->dehydrated(),

                        DatePicker::make('shipping_date')
                            ->label('Shipping Date')
                            ->required()
                            ->disabled()
                            ->dehydrated(),

                        Select::make('status')
                            ->label('Status')
                            ->options([
                                'PENDING' => 'Pending',
                                'PICKING' => 'Picking',
                                'SHORTAGE' => 'Shortage',
                                'COMPLETED' => 'Completed',
                                'CLOSED' => 'Closed',
                            ])
                            ->required()
                            ->default('PENDING'),
                    ])
                    ->columns(2),
            ]);
    }
}
